import { Page, PageHeader, ScrollScreen, Section, AdaptiveGrid, AdaptiveGridItem, ChartPanel, MetricTrendCard, BreakdownPanel, MetricDelta, Card, Text, VStack, HStack, Button, DonutChart, Sparkline, AdaptiveDataTable, type DataColumn } from '@precision-calm/ui';
import { GroupedBarChart, Histogram, MultiLineChart } from '@precision-calm/visualization-advanced';
import { useReferenceCopy } from '../ReferenceCopy';
import { showcaseBreakdown, showcaseSegmentComparison, showcaseSeries, showcaseTable, showcaseTrend } from '../showcaseData';

export default function AnalyticsShowcaseScreen() {
  const copy = useReferenceCopy();
  const columns: DataColumn<(typeof showcaseTable)[number]>[] = [{ key: 'label', label: copy('Account'), render: (row) => row.label, primary: true }, { key: 'value', label: copy('Value'), render: (row) => row.value, numeric: true }, { key: 'status', label: copy('Status'), render: (row) => row.status }];
  return <ScrollScreen><Page width="dashboard" header={<PageHeader eyebrow={copy('ANALYTICS / OVERVIEW')} title={copy('A calm view of growth')} description={copy('A reusable analytics composition connecting trend, comparison, distribution, and accountable detail without turning the page into a chart gallery.')} />}>
    <Section><AdaptiveGrid><AdaptiveGridItem><MetricTrendCard label={copy('Active accounts')} value="18,420" delta="12.8% vs prior period" deltaDirection="up" deltaTone="positive" context={copy('Healthy acquisition')} trend={<Sparkline data={showcaseTrend.map((item) => ({ label: item.label, value: item.values.current ?? 0 }))} name={copy('Active accounts trend')} />}/></AdaptiveGridItem><AdaptiveGridItem><MetricTrendCard label={copy('Net expansion')} value="$104.3k" delta="8.4% vs prior period" deltaDirection="up" deltaTone="positive" context={copy('Above target')} /></AdaptiveGridItem><AdaptiveGridItem><MetricTrendCard label={copy('Retention floor')} value="91.4%" delta="1.2 pts below target" deltaDirection="down" deltaTone="warning" context={copy('Watch enterprise cohort')} /></AdaptiveGridItem></AdaptiveGrid></Section>
    <Section><ChartPanel title={copy('Monthly performance')} description={copy('Current period against the previous period and operating target.')} summary={<MetricDelta direction="up" tone="positive" label={copy('Current period is ahead of target in four of six months.')} />}><MultiLineChart data={showcaseTrend} series={showcaseSeries} name={copy('Monthly performance')} showLegend showDataTable /></ChartPanel></Section>
    <Section><AdaptiveGrid><AdaptiveGridItem><BreakdownPanel title={copy('Account mix')} description={copy('Composition by customer segment.')} total="100%"><DonutChart data={showcaseBreakdown} name={copy('Account mix')} size="compact" showLegend showDataTable /></BreakdownPanel></AdaptiveGridItem><AdaptiveGridItem><ChartPanel title={copy('Distribution of value')} description={copy('A bounded distribution helps explain the headline metric.')}><Histogram data={[12, 18, 22, 23, 27, 31, 32, 34, 35, 40, 42, 44, 48, 52, 58, 64]} name={copy('Distribution of value')} bins={6} showDataTable /></ChartPanel></AdaptiveGridItem></AdaptiveGrid></Section>
    <Section><ChartPanel title={copy('Segment comparison')} description={copy('Grouped bars make category comparison explicit.')}><GroupedBarChart data={showcaseSegmentComparison} series={showcaseSeries.slice(0, 2)} name={copy('Segment comparison')} showLegend showDataTable /></ChartPanel></Section>
    <Section><Card><VStack gap="md"><VStack gap="xs"><Text variant="h2">{copy('Recent account movement')}</Text><Text tone="secondary">{copy('The detail layer keeps the narrative accountable and exportable.')}</Text></VStack><AdaptiveDataTable columns={columns} rows={showcaseTable} keyExtractor={(row) => row.label} /></VStack></Card></Section>
  </Page></ScrollScreen>;
}
