import { Page, PageHeader, ScrollScreen, Section, AdaptiveGrid, AdaptiveGridItem, ChartPanel, MetricTrendCard, BreakdownPanel, Card, Text, VStack, HStack, Button, DonutChart, AdaptiveDataTable, type DataColumn } from '@precision-calm/ui';
import { MultiLineChart, WaterfallChart, BulletChart } from '@precision-calm/visualization-advanced';
import { useReferenceCopy } from '../ReferenceCopy';
import { showcaseBreakdown, showcaseSeries, showcaseTable, showcaseTrend, showcaseWaterfall } from '../showcaseData';

export default function FinanceShowcaseScreen() {
  const copy = useReferenceCopy();
  const columns: DataColumn<(typeof showcaseTable)[number]>[] = [{ key: 'label', label: copy('Entity'), render: (row) => row.label, primary: true }, { key: 'value', label: copy('Period value'), render: (row) => row.value, numeric: true }, { key: 'status', label: copy('Review state'), render: (row) => row.status }];
  return <ScrollScreen><Page width="dashboard" header={<PageHeader eyebrow={copy('FINANCE / OPERATIONS')} title={copy('Value, contribution, and control')} description={copy('A neutral financial-operations composition demonstrating signed change and reference levels without embedding advice or financial business rules.')} />}>
    <Section><AdaptiveGrid><AdaptiveGridItem><MetricTrendCard label={copy('Managed value')} value="$1.04m" delta="6.2% above prior period" deltaDirection="up" deltaTone="positive" context={copy('Reference value')} /></AdaptiveGridItem><AdaptiveGridItem><MetricTrendCard label={copy('Net movement')} value="+$203k" delta="Expansion offsets churn" deltaDirection="up" deltaTone="positive" context={copy('Semantic tone supplied by the product')} /></AdaptiveGridItem><AdaptiveGridItem><MetricTrendCard label={copy('Operating target')} value="$1.00m" delta="4.3% above target" deltaDirection="up" deltaTone="positive" context={copy('Target remains visible')} /></AdaptiveGridItem></AdaptiveGrid></Section>
    <Section><ChartPanel title={copy('Period comparison')} description={copy('Current and previous values share one ordered x-axis.')}><MultiLineChart data={showcaseTrend} series={showcaseSeries.slice(0, 2)} name={copy('Period comparison')} showLegend showDataTable /></ChartPanel></Section>
    <Section><AdaptiveGrid><AdaptiveGridItem><BreakdownPanel title={copy('Allocation mix')} description={copy('Composition is readable without relying on color alone.')} total="$1.04m"><DonutChart data={showcaseBreakdown} name={copy('Allocation mix')} size="compact" showLegend showDataTable /></BreakdownPanel></AdaptiveGridItem><AdaptiveGridItem><ChartPanel title={copy('Contribution bridge')} description={copy('Increases, decreases, and total are distinct semantic marks.')}><WaterfallChart data={showcaseWaterfall} name={copy('Contribution bridge')} /></ChartPanel></AdaptiveGridItem></AdaptiveGrid></Section>
    <Section><ChartPanel title={copy('Target attainment')} description={copy('Reference mechanics remain generic; the product supplies meaning.')}><BulletChart value={82} target={75} ranges={[45, 65, 85, 100]} name={copy('Target attainment')} valueFormatter={(value) => `${Math.round(value)}%`} /></ChartPanel></Section>
    <Section><Card><VStack gap="md"><VStack gap="xs"><Text variant="h2">{copy('Account detail')}</Text><Text tone="secondary">{copy('A dense view remains subordinate to the summary narrative.')}</Text></VStack><AdaptiveDataTable columns={columns} rows={showcaseTable} keyExtractor={(row) => row.label} /></VStack></Card></Section>
  </Page></ScrollScreen>;
}
