import { useState } from 'react';
import { Alert } from 'react-native';
import { usePrecisionRouter } from '@precision-calm/navigation-router';
import { GOLDEN_PATTERN_IDS, formatCurrency, type GoldenPatternId } from '@precision-calm/platform';
import { ScrollScreen } from '@precision-calm/ui';
import { HStack, Text, VStack } from '@precision-calm/ui';
import { Badge, Button, Card, Chip } from '@precision-calm/ui';
import { TextField, FormSection } from '@precision-calm/ui';
import { AlertBanner } from '@precision-calm/ui';
import { AdaptiveDataTable, KeyValueList, ListRow, Metric, MetricGroup, type DataColumn } from '@precision-calm/ui';
import { LineChart, ProgressBar } from '@precision-calm/ui';
import {
  AnalyticsLayout, AuthenticationLayout, CreateEditFormLayout, DashboardLayout, DataWorkspaceLayout, DetailLayout,
  EmptyStartLayout, FeedListLayout, FullScreenWorkflowLayout, MasterDetailPageLayout, OverlayWorkflowLayout,
  ProfileLayout, SearchResultsLayout, SettingsLayout, WizardLayout,
} from '@precision-calm/ui';

type DemoRow={id:string;name:string;issuer:string;value:number};
const rows:DemoRow[]=[{id:'vx',name:'Venture X',issuer:'Capital One',value:1220},{id:'gold',name:'Gold Card',issuer:'American Express',value:980},{id:'sapphire',name:'Sapphire Preferred',issuer:'Chase',value:690}];
const columns:readonly DataColumn<DemoRow>[]=[{key:'name',label:'Card',primary:true,weight:'lg',render:r=>r.name},{key:'issuer',label:'Issuer',render:r=>r.issuer},{key:'value',label:'Value',numeric:true,weight:'sm',render:r=>formatCurrency(r.value)}];
const trend=[{label:'Jan',value:6200},{label:'Feb',value:6480},{label:'Mar',value:6310},{label:'Apr',value:6840},{label:'May',value:7010},{label:'Jun',value:7380},{label:'Jul',value:7210},{label:'Aug',value:8420}];

export default function GoldenPatternsReferenceScreen(){
  const router=usePrecisionRouter();
  const [index,setIndex]=useState(0);
  const [overlayOpen,setOverlayOpen]=useState(false);
  const [name,setName]=useState('Travel setup');
  const id=GOLDEN_PATTERN_IDS[index]??'dashboard';
  const next=()=>setIndex((value)=>(value+1)%GOLDEN_PATTERN_IDS.length);
  const actions=<HStack gap="sm"><Badge label={`${index+1} / ${GOLDEN_PATTERN_IDS.length}`} tone="info"/><Button label="Next pattern" size="sm" variant="secondary" onPress={next}/><Button label="Home" size="sm" variant="ghost" onPress={()=>router.replace('/')}/></HStack>;
  return <ScrollScreen>{renderPattern(id,{actions,overlayOpen,setOverlayOpen,name,setName})}</ScrollScreen>;
}

type RenderContext={actions:React.ReactNode;overlayOpen:boolean;setOverlayOpen:(open:boolean)=>void;name:string;setName:(value:string)=>void};
function renderPattern(id:GoldenPatternId,ctx:RenderContext){
  const common={eyebrow:`GOLDEN PATTERN / ${id.toUpperCase()}`,actions:ctx.actions};
  const metric=<MetricGroup><Metric label="Tracked value" value="$8,420" trend="+14.2% YTD" trendTone="positive"/><Metric label="Annual fees" value="$1,215" trend="6 active products"/><Metric label="Upcoming value" value="$1,090" trend="3 benefits"/></MetricGroup>;
  const list=<Card><VStack gap="sm"><ListRow title="Venture X" subtitle="Capital One · Updated 4 min ago" leadingIcon="creditCard" trailing={<Badge label="Active" tone="positive"/>}/><ListRow title="Gold Card" subtitle="American Express · Review annual fee" leadingIcon="creditCard" trailing={<Badge label="Review" tone="warning"/>}/><ListRow title="Sapphire Preferred" subtitle="Chase · Travel category" leadingIcon="creditCard"/></VStack></Card>;
  switch(id){
    case 'dashboard': return <DashboardLayout {...common} title="Dashboard" description="Primary overview pattern for consumer or operational products." metrics={metric} primary={<Card><VStack gap="lg"><Text variant="h2">Value trend</Text><LineChart data={trend} area/></VStack></Card>} secondary={<Card><VStack gap="md"><Text variant="h3">Attention</Text><AlertBanner tone="warning" title="Annual fee in 12 days" message="Review retention value before renewal."/></VStack></Card>} activity={list}/>;
    case 'feed-list': return <FeedListLayout {...common} title="Activity feed" description="Dense chronological or entity collections with optional controls." controls={<HStack gap="sm"><Chip label="All" selected onPress={()=>{}}/><Chip label="Rewards" onPress={()=>{}}/><Chip label="Spend" onPress={()=>{}}/></HStack>} content={list}/>;
    case 'search-results': return <SearchResultsLayout {...common} title="Search results" description="Results remain primary; compact layouts place filters before the result set." summary={<Text tone="secondary">24 results for “travel”</Text>} filters={<Card><VStack gap="md"><Text variant="h3">Filters</Text><Button label="Issuer" variant="secondary" onPress={()=>{}}/><Button label="Annual fee" variant="secondary" onPress={()=>{}}/><Button label="Status" variant="secondary" onPress={()=>{}}/></VStack></Card>} results={list}/>;
    case 'data-workspace': return <DataWorkspaceLayout {...common} title="Data workspace" description="Wide operational surface with optional inspector instead of a squeezed mobile table." controls={<HStack gap="sm"><Button label="Filter" variant="secondary" onPress={()=>{}}/><Button label="Export" variant="outline" onPress={()=>{}}/></HStack>} data={<AdaptiveDataTable rows={rows} columns={columns} keyExtractor={r=>r.id}/>} inspector={<Card><KeyValueList items={[{key:'scope',label:'Scope',value:'All cards'},{key:'updated',label:'Updated',value:'4 min ago'},{key:'rows',label:'Rows',value:rows.length}]}/></Card>}/>;
    case 'detail': return <DetailLayout {...common} title="Venture X" description="Entity detail pattern with hero summary and contextual aside." hero={<Card>{metric}</Card>} details={<Card><KeyValueList items={[{key:'issuer',label:'Issuer',value:'Capital One'},{key:'fee',label:'Annual fee',value:'$395'},{key:'opened',label:'Opened',value:'May 2026'}]}/></Card>} aside={<Card><VStack gap="md"><Text variant="h3">Actions</Text><Button label="Edit" onPress={()=>{}}/><Button label="Archive" variant="outline" onPress={()=>{}}/></VStack></Card>}/>;
    case 'master-detail': return <MasterDetailPageLayout {...common} title="Cards" description="Selection and detail coexist only when the layout capability supports it." master={list} detail={<Card><VStack gap="lg"><Text variant="h2">Venture X</Text><Text tone="secondary">Expanded layouts show both panes; compact layouts preserve one focused workflow.</Text><KeyValueList items={[{key:'value',label:'Value',value:'$1,220'},{key:'fee',label:'Annual fee',value:'$395'}]}/></VStack></Card>}/>;
    case 'create-edit-form': return <CreateEditFormLayout {...common} title="Edit setup" description="Single-purpose create/edit flow with centralized form action hierarchy." form={<FormSection title="Basics" description="Labels remain visible and validation behavior is system-owned."><TextField label="Nickname" value={ctx.name} onChangeText={ctx.setName}/><TextField label="Institution" value="Capital One" onChangeText={()=>{}}/></FormSection>} primaryAction={<Button label="Save changes" onPress={()=>Alert.alert('Saved')}/>} secondaryAction={<Button label="Cancel" variant="ghost" onPress={()=>{}}/>}/>;
    case 'wizard': return <WizardLayout {...common} title="Connect account" description="Progressive multi-step workflows keep progress and actions in stable locations." progress={<ProgressBar value={0.5} label="Step 2 of 4"/>} step={<Card><VStack gap="md"><Text variant="h2">Confirm institution</Text><Text tone="secondary">Review the selected provider before continuing.</Text><KeyValueList items={[{key:'bank',label:'Institution',value:'Example Bank'},{key:'type',label:'Connection',value:'Secure OAuth'}]}/></VStack></Card>} primaryAction={<Button label="Continue" onPress={()=>{}}/>} secondaryAction={<Button label="Back" variant="secondary" onPress={()=>{}}/>}/>;
    case 'settings': return <SettingsLayout {...common} title="Settings" description="Settings become a master/detail workspace on larger layouts and a safe stack on compact layouts." navigation={<Card><VStack gap="sm"><Button label="General" variant="secondary" onPress={()=>{}}/><Button label="Notifications" variant="ghost" onPress={()=>{}}/><Button label="Privacy" variant="ghost" onPress={()=>{}}/></VStack></Card>} content={<Card><VStack gap="lg"><Text variant="h2">General</Text><ListRow title="Appearance" subtitle="System theme"/><ListRow title="Density" subtitle="Comfortable"/><ListRow title="Language" subtitle="English"/></VStack></Card>}/>;
    case 'profile': return <ProfileLayout {...common} title="Profile" description="Identity summary followed by independent profile sections." summary={<Card><VStack gap="sm"><Text variant="h2">Alex Kim</Text><Text tone="secondary">alex@example.com</Text><Badge label="Verified" tone="positive"/></VStack></Card>} sections={[<Card key="personal"><VStack gap="md"><Text variant="h3">Personal information</Text><ListRow title="Name" trailing={<Text>Alex Kim</Text>}/><ListRow title="Timezone" trailing={<Text>Central</Text>}/></VStack></Card>,<Card key="security"><VStack gap="md"><Text variant="h3">Security</Text><ListRow title="Passkey" trailing={<Badge label="Enabled" tone="positive"/>}/><ListRow title="Recovery" trailing={<Badge label="Ready" tone="positive"/>}/></VStack></Card>]}/>;
    case 'authentication': return <AuthenticationLayout brand={<Text variant="micro" tone="secondary">PRECISION CALM</Text>} title="Welcome back" description="Authentication stays focused and deliberately narrow on large screens." form={<VStack gap="lg"><TextField label="Email" value="alex@example.com" onChangeText={()=>{}}/><TextField label="Password" value="example-password" onChangeText={()=>{}} secureTextEntry/><Button label="Sign in" onPress={()=>{}}/></VStack>} footer={<HStack justify="between"><Button label="Next pattern" size="sm" variant="ghost" onPress={()=>{const current=GOLDEN_PATTERN_IDS.indexOf('authentication');ctx.actions && void current;}}/>{ctx.actions}</HStack>}/>;
    case 'analytics': return <AnalyticsLayout {...common} title="Analytics" description="Metrics and visualizations scale independently while insight context moves to an aside." metrics={metric} primaryChart={<Card><VStack gap="lg"><Text variant="h2">Value over time</Text><LineChart data={trend} area/></VStack></Card>} insights={<Card><VStack gap="md"><Text variant="h3">Insights</Text><AlertBanner tone="positive" title="Value increased" message="Synthetic tracked value is up from January."/></VStack></Card>}/>;
    case 'empty-start': return <EmptyStartLayout {...common} title="Cards" description="New-user and zero-data experiences preserve hierarchy rather than showing a blank page." emptyTitle="Add your first card" emptyMessage="Start with one account. The platform will build the rest of the experience around real content." actionLabel="Add card" onAction={()=>Alert.alert('Start')} secondaryLabel="Learn more" onSecondary={()=>{}}/>;
    case 'full-screen-workflow': return <FullScreenWorkflowLayout {...common} title="Review changes" description="Focused workflows keep one dominant task and stable exit/continue actions." status={<AlertBanner tone="info" title="3 changes ready" message="Nothing is submitted until you confirm."/>} content={<Card><KeyValueList items={[{key:'nickname',label:'Nickname',value:ctx.name},{key:'issuer',label:'Issuer',value:'Capital One'},{key:'status',label:'Status',value:'Active'}]}/></Card>} primaryAction={<Button label="Confirm changes" onPress={()=>Alert.alert('Confirmed')}/>} secondaryAction={<Button label="Back" variant="secondary" onPress={()=>{}}/>}/>;
    case 'overlay-workflow': return <OverlayWorkflowLayout {...common} title="Overlay workflow" description="Page context stays intact while a shared dialog or sheet owns transient decisions." base={<Card><VStack gap="lg"><Text variant="h2">Context remains visible</Text><Text tone="secondary">Open the system-owned confirmation overlay without feature-level positioning or z-index.</Text><Button label="Open confirmation" onPress={()=>ctx.setOverlayOpen(true)}/></VStack></Card>} open={ctx.overlayOpen} onOpenChange={ctx.setOverlayOpen} presentation="dialog" overlayTitle="Confirm review" overlayDescription="This uses the centralized overlay manager." overlayContent={<Text tone="secondary">The workflow has explicit cancel and confirm actions.</Text>} overlayActions={<HStack gap="sm"><Button label="Cancel" variant="secondary" onPress={()=>ctx.setOverlayOpen(false)}/><Button label="Confirm" onPress={()=>ctx.setOverlayOpen(false)}/></HStack>}/>;
  }
}
