import { Page, PageHeader, ScrollScreen, Section, AdaptiveGrid, AdaptiveGridItem, ChartPanel, MetricTrendCard, BreakdownPanel, Card, Text, VStack, HStack, StatusIndicator, Timeline, Button, AdaptiveDataTable, type DataColumn } from '@precision-calm/ui';
import { MultiLineChart, RangeBarChart } from '@precision-calm/visualization-advanced';
import { useReferenceCopy } from '../ReferenceCopy';
import { showcaseRanges, showcaseSeries, showcaseTable, showcaseTrend } from '../showcaseData';

export default function MonitoringShowcaseScreen() {
  const copy = useReferenceCopy();
  const columns: DataColumn<(typeof showcaseTable)[number]>[] = [{ key: 'label', label: copy('Service'), render: (row) => row.label, primary: true }, { key: 'value', label: copy('Current'), render: (row) => row.value, numeric: true }, { key: 'status', label: copy('Health'), render: (row) => row.status }];
  return <ScrollScreen><Page width="dashboard" header={<PageHeader eyebrow={copy('MONITORING / OPERATIONS')} title={copy('Know what needs attention')} description={copy('A dense operational composition connecting health, thresholds, anomalies, and recent events with deterministic sample data.')} />}>
    <Section><HStack gap="sm" align="stretch"><StatusIndicator label={copy('All systems operational')} tone="positive" /><StatusIndicator label={copy('2 services under watch')} tone="warning" /></HStack></Section>
    <Section><AdaptiveGrid><AdaptiveGridItem><MetricTrendCard label={copy('Availability')} value="99.98%" delta="0.04 pts above target" deltaDirection="up" deltaTone="positive" context={copy('Last 24 hours')} /></AdaptiveGridItem><AdaptiveGridItem><MetricTrendCard label={copy('P95 latency')} value="182ms" delta="18ms above target" deltaDirection="down" deltaTone="warning" context={copy('Checkout path')} /></AdaptiveGridItem><AdaptiveGridItem><MetricTrendCard label={copy('Open incidents')} value="2" delta="1 new in the last hour" deltaDirection="up" deltaTone="negative" context={copy('Acknowledgement required')} /></AdaptiveGridItem></AdaptiveGrid></Section>
    <Section><ChartPanel title={copy('Service health trend')} description={copy('The selected threshold is visible in the surrounding operational context.')}><MultiLineChart data={showcaseTrend} series={showcaseSeries} name={copy('Service health trend')} showLegend showDataTable /></ChartPanel></Section>
    <Section><AdaptiveGrid><AdaptiveGridItem><BreakdownPanel title={copy('Threshold windows')} description={copy('Normal operating range by service.')}><RangeBarChart data={showcaseRanges} name={copy('Threshold windows')} /></BreakdownPanel></AdaptiveGridItem><AdaptiveGridItem><Card><VStack gap="md"><Text variant="h3">{copy('Recent events')}</Text><Timeline label={copy('Recent monitoring events')} items={[{ id: 'event-1', title: copy('Checkout latency crossed watch threshold'), timestamp: copy('12 minutes ago'), tone: 'warning', statusLabel: copy('Watch'), description: copy('The service remains available while the team reviews the latest deploy.') }, { id: 'event-2', title: copy('Search recovered'), timestamp: copy('48 minutes ago'), tone: 'positive', statusLabel: copy('Recovered'), description: copy('Error rate returned to the normal range.') }]} /></VStack></Card></AdaptiveGridItem></AdaptiveGrid></Section>
    <Section><Card><VStack gap="md"><Text variant="h2">{copy('Service breakdown')}</Text><AdaptiveDataTable columns={columns} rows={showcaseTable} keyExtractor={(row) => row.label} /></VStack></Card></Section>
  </Page></ScrollScreen>;
}
