import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const root = process.cwd();
const required = [
  'package.json',
  'tsconfig.base.json',
  'apps/reference/package.json',
  'apps/reference/app.config.ts',
  'apps/reference/unistyles.ts',
  'packages/tokens/src/index.ts',
  'packages/platform/src/index.ts',
  'packages/primitives/src/index.ts',
  'packages/icons/src/index.ts',
  'packages/layouts/src/index.ts',
  'packages/components/src/index.ts',
  'packages/forms/src/index.ts',
  'packages/form-rhf/src/index.tsx',
  'packages/navigation/src/index.ts',
  'packages/navigation-router/src/index.tsx',
  'packages/overlays/src/index.ts',
  'packages/lists/src/index.ts',
  'packages/data-display/src/index.ts',
  'packages/platform/src/data.ts',
  'packages/platform/src/visualization.ts',
  'packages/visualization/src/index.ts',
  'packages/platform/src/feedback.ts',
  'packages/feedback/src/index.ts',
  'packages/platform/src/accessibility.ts',
  'packages/motion/src/index.ts',
  'packages/accessibility/src/index.ts',
  'packages/platform/src/patterns.ts',
  'packages/patterns/src/index.ts',
  'packages/layouts/src/PriorityActionBar.tsx',
  'packages/layouts/src/AdaptiveSplit.tsx',
  'packages/layouts/src/SidebarLayout.tsx',
  'packages/platform/src/overflow.ts',
  'scripts/check-layout-contracts.mjs',
  'scripts/test-layout-solvers.mjs',
  'scripts/check-form-contracts.mjs',
  'scripts/test-form-contracts.mjs',
  'scripts/check-navigation-contracts.mjs',
  'scripts/test-navigation-contracts.mjs',
  'scripts/check-overlay-contracts.mjs',
  'scripts/test-overlay-contracts.mjs',
  'scripts/check-list-contracts.mjs',
  'scripts/test-list-contracts.mjs',
  'scripts/check-data-contracts.mjs',
  'scripts/test-data-contracts.mjs',
  'scripts/check-visualization-contracts.mjs',
  'scripts/test-visualization-contracts.mjs',
  'scripts/check-feedback-contracts.mjs',
  'scripts/test-feedback-contracts.mjs',
  'scripts/check-accessibility-motion-contracts.mjs',
  'scripts/test-accessibility-motion-contracts.mjs',
  'scripts/check-pattern-contracts.mjs',
  'scripts/test-pattern-contracts.mjs',
  'packages/testing/src/index.ts',
  'packages/testing/src/certification.ts',
  'scripts/check-certification-contracts.mjs',
  'scripts/test-certification-matrix.mjs',
  'apps/reference/app/system.tsx',
  'apps/reference/app/stress.tsx',
  'playwright.config.ts',
  'tests/e2e/web/reference.spec.ts',
  'tests/native/reference-flow.yaml',
  'packages/create-precision-app/package.json',
  'packages/create-precision-app/bin/create-precision-app.mjs',
  'scripts/test-generator.mjs',
  'docs/GENERATOR.md',
  'packages/tokens/src/brand.ts',
  'apps/reference/brand.ts',
  'docs/CERTIFICATION.md',
  'docs/BRANDING.md',
  'docs/PORTABILITY.md',
  'scripts/release-readiness.mjs',
  'precision.compatibility.json',
  'packages/ui/package.json',
  'packages/ui/src/index.ts',
  'packages/runtime/package.json',
  'packages/runtime/src/index.ts',
  'packages/runtime/src/services.tsx',
  'apps/reference/services.ts',
  'apps/reference/app/services.tsx',
  'scripts/test-service-runtime.mjs',
  'scripts/check-package-manifests.mjs',
  'scripts/check-public-api.mjs',
  'docs/PUBLIC_API.md',
  'packages/migrate-precision-app/package.json',
  'packages/migrate-precision-app/bin/precision-migrate-audit.mjs',
  'scripts/test-migration-audit.mjs',
  'docs/MIGRATION.md',
  'precision.api.json',
  'scripts/api-snapshot.mjs',
  'packages/precision-doctor/package.json',
  'packages/precision-doctor/bin/precision-doctor.mjs',
  'scripts/test-doctor.mjs',
  'packages/linking/src/index.ts',
  'packages/linking-expo/src/index.ts',
  'scripts/check-linking-contracts.mjs',
  'scripts/test-linking-contracts.mjs',
  'packages/auth/src/index.ts',
  'packages/auth/src/access.ts',
  'packages/auth/src/returnIntent.ts',
  'packages/runtime/src/auth.tsx',
  'scripts/check-auth-contracts.mjs',
  'scripts/test-auth-contracts.mjs',
  'scripts/test-auth-runtime.mjs',
  'apps/reference/auth.ts',
  'apps/reference/app/auth-session.tsx',
  'apps/reference/app/sign-in.tsx',
  'apps/reference/app/session-loading.tsx',
  'apps/reference/app/session-error.tsx',
  'docs/AUTH_PROTECTED_ROUTES.md',
  'packages/authorization/src/index.ts',
  'packages/authorization/src/contracts.ts',
  'packages/authorization/src/policy.ts',
  'packages/runtime/src/authorization.tsx',
  'scripts/check-authorization-contracts.mjs',
  'scripts/test-authorization-contracts.mjs',
  'scripts/test-authorization-runtime.mjs',
  'apps/reference/app/authorization.tsx',
  'apps/reference/app/admin-demo.tsx',
  'docs/AUTHORIZATION_CAPABILITIES.md',
  'docs/GATE36_RESTORATION_NOTE.md',
];

const missing = required.filter((file) => !fs.existsSync(path.join(root, file)));
if (missing.length) {
  console.error('Missing required platform files:\n' + missing.map((x) => `- ${x}`).join('\n'));
  process.exit(1);
}

for (const jsonFile of ['package.json', 'apps/reference/package.json']) {
  JSON.parse(fs.readFileSync(path.join(root, jsonFile), 'utf8'));
}

console.log(`Precision Calm validation passed (${required.length} required files present).`);
